server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://ec2-3-222-74-92.compute-1.amazonaws.com:5432/de27deoh0fp9p0
    username: khqbzbqqoigist
    password: 447eaf3bdf156c22f6066fa03abe4fcb0c999e9911cac48b0bcef4d255b4717e
  jpa:
    hibernate:
      ddl-auto: update
#              ddl-auto: create
    show-sql: true
    open-in-view: true
    properties:
        hibernate:
          enable_lazy_load_no_trans: true
  sql:
    init:
#      mode: always
      mode: never
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
jwt:
  secret-key: nimakerakshusuzjasndjandoasndasndiasndasndkasndkasdnsaldlaskdn